### ISSUE TITLE
Remove Lombok

### ISSUE THREAD

**Issue by michael-schnell** [valdasraps/esj#5]
I started working on #3 but Lombok makes it hard to build the project out-of-the box. I propose removing Lombok ("less magic" as Greg Young would say) and switch to simple getters,
As I have not the time to wait for your answer, I will go for that solution on the fork I'm working on,

Some more argument against using Lombox can be found here:http://stackoverflow.com/questions/15518405/lombok-slowing-down-build-process-in-large-project (Especially Olivier Croisier answered Mar 20 '13 at 9:42)

**Comment by valdasraps** [comment]
I'm not religious about Lombok and agree that code would be cleaner if less annotations are processed. You can go ahead and remove Lombok, I can merge it once done.

**Comment by michael-schnell** [comment]
Great. I already fixed this on the branch: https://github.com/fuinorg/esj
