### ISSUE TITLE
ESJ should not create executor services itself

### ISSUE THREAD

**Issue by michael-schnell** [valdasraps/esj#8]
In the code there are some places where ```Executors.newSingleThreadExecutor()``` or ```Executors.newFixedThreadPool(...)``` is used. Using ESJ in a JEE application server it would not be possible to create threads that way.

We should just always make "ExecutorService" a constructor argument.

**Comment by valdasraps** [comment]
Will add constructors with ExecutorService as an argument. Work in progress.
